name: dropout_own_sim_permuteNonzero

samplesheet: "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/own_sim/samplesheet.tsv"
#specify output directory
output_dir: "/data/akalin/akollot/anglemania_benchmark/simulated/with_dropout/own_sim/dropout_own_sim_permuteNonzero"
# specify sub dir in output directory for outputs of the two separate rules
out_preprocessed: "preprocessed/"
out_integration: "integration/"
out_metrics: "metrics/"

batch_key: "Batch"
label_key: "Group"
anglemania_mode: "cosine"
permutation_function: "permute_nonzero"
n_genes: 2000

integration_methods: ["scanorama", "scvi"] # "seurat", "scanvi", "harmony"
gene_selection: [ "hvg", "angl"] #"full", "rand", 
gpu: False

