name: btvr_sanity_check

samplesheet: "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/samplesheet_btvr_sanity_check.tsv"

output_dir: "/data/akalin/akollot/anglemania_benchmark/simulated/btvr_sanity_check/"
out_preprocessed: "preprocessed/"
out_integration: "integration/"
out_metrics: "metrics/"
out_embedding: "embedding/"

batch_key: "Batch"
label_key: "Group"
anglemania_mode: "cosine"
permutation_function: "sample"
normalization_mode: "classical" # "classical" (CP10K + log1p) | "pflog1ppf" (shifted-CLR)
n_genes: 2000

integration_methods: ["scvi", "scanorama"]
gene_selection: ["hvg", "angl", "topbtvr", "bottombtvr"]
gpu: false
