---
title: "bm_simulated_visualization"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/")})
output:
    html_document:
      toc: yes
      toc_float:
        collapsed: no
        smooth_scroll: no
      df_print: paged

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height = 10)
knitr::opts_chunk$set(fig.width = 14)
```

```{r}
.libPaths(.Library)
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
library(Seurat)
library(anndataR)
library(bigstatsr)
# devtools::load_all("../../anglemania")
library(matrixStats)
```

```{r}
# basedir <- "/data/akalin/akollot/anglemania_benchmark/simulated/preprocessed/"
# #sce-simulated-splatter.batch.facLoc1_de.facLoc0.1_ngroup5_angl.h5ad

# sample <- "sce-simulated-splatter.batch.facLoc0.1_de.facLoc0.1_ngroup10_hvg.h5ad"
# infile <- paste0(basedir, sample)
# se <- anndataR::read_h5ad("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/sce-simulated-splatter.batch.facLoc0.9_de.facLoc0.1_ngroup5.h5ad", to = "Seurat")
# se
# angl <- create_anglem(se, batch_key = "Batch")

# angl <- big_anglemanise(angl,
#                         method = "rho",
#                         zscore_mean_threshold = 2,
#                         zscore_sn_threshold  = 2,
#                         max_n_genes = 2000)


# angl@integration_genes$genes
# test <- angl@integration_genes$info
# test
```

# Load metrics
```{r}
metrics <- read.csv("/data/akalin/akollot/anglemania_benchmark/simulated/archived/metrics/combined_metrics.tsv", sep = "\t", stringsAsFactors = FALSE)

facloc_batch <- sapply(metrics$sample, function(x){
    x <- stringr::str_split(x, "_")[[1]][1]
    x <- gsub("sce-simulated-splatter.batch.facLoc", "", x)
    x <- as.numeric(x)
})

facloc_bio <- sapply(metrics$sample, function(x){
    x <- stringr::str_split(x, "_")[[1]][2]
    x <- gsub("de.facLoc", "", x)
    x <- as.numeric(x)
})

batch_bio_ratio <- facloc_batch / facloc_bio
metrics <- cbind(metrics, facloc_batch, facloc_bio, batch_bio_ratio)
head(metrics)
colnames(metrics)
# metrics["Batch"] = metrics[["ASW_label/batch", "PCR_batch", "graph_conn"]].mean(axis=1)
# metrics["Bio"] = metrics[["ASW_label", "isolated_label_silhouette"]].mean(axis=1)
bio_metrics <- c("cLISI", "ARI_cluster.label", "NMI_cluster.label", "ASW_label", "isolated_label_F1", "isolated_label_silhouette")
batch_metrics <- c("kBET", "ASW_label.batch", "iLISI")

# calculate weighted mean with 0.6 for bio and 0.4 for batch
# first min max scale every metrics
#metrics_scaled = (metrics - metrics.min()) / (metrics.max() - metrics.min())
min_max_norm <- function(x) {
    (x - min(x)) / (max(x) - min(x))
  }
metrics_sub <- metrics[metrics$integration_method == "harmony",]

metrics_scaled <- metrics_sub %>%
  # scale data
  mutate(across(all_of(bio_metrics), ~ min_max_norm(.) %>% as.vector)) %>%
  mutate(across(all_of(batch_metrics), ~ min_max_norm(.) %>% as.vector)) %>%
  rowwise() %>%
  mutate(
    bio_score = mean(c_across(all_of(bio_metrics))),
    batch_score = mean(c_across(all_of(batch_metrics))),
    overall_score = 0.6 * bio_score + 0.4 * batch_score
  ) 

# View(metrics_scaled)
```

```{r}
metrics_scaled %>%
  ggplot(aes(log2(batch_bio_ratio), overall_score))+
  geom_line(aes(color = gene_selection))
```

```{r}

p <- metrics_scaled %>% 
  ggplot(aes(x = facloc_batch, y = facloc_bio))+
  geom_tile(aes(fill = overall_score))+
  facet_wrap(~gene_selection)
p

metrics_scaled %>%
  ungroup() %>%
  summarize(best_gene_selection = gene_selection[which.max(overall_score)], .by = c(facloc_batch, facloc_bio)) %>%
  ggplot(aes(x = facloc_batch, y = facloc_bio))+
  geom_tile(aes(fill = best_gene_selection))

# make a line plot where every gene_selection is one line and facloc_batch is x and facloc_bio is y
metrics_scaled %>%
  ggplot(aes(x = facloc_batch, y = overall_score))+
  geom_line(aes(color = gene_selection))+
  facet_wrap(~facloc_bio) +
  ggtitle(paste0("Overall integration score split by biological variability. Integration method: ", unique(metrics_scaled$integration_method)))
```

```{r}
metrics_scaled %>%
  ggplot(aes(x = facloc_batch, y = bio_score))+
  geom_line(aes(color = gene_selection))+
  facet_wrap(~facloc_bio) +
  ggtitle(paste0("Overall integration score split by biological variability. Integration method: ", unique(metrics_scaled$integration_method)))

metrics_scaled %>%
  ggplot(aes(x = facloc_batch, y = batch_score))+
  geom_line(aes(color = gene_selection))+
  facet_wrap(~facloc_bio) +
  ggtitle(paste0("Overall integration score split by biological variability. Integration method: ", unique(metrics_scaled$integration_method)))
```

