---
title: "bm_simulated_visualization"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/")})
output:
    html_document:
      toc: yes
      toc_float:
        collapsed: no
        smooth_scroll: no
      df_print: paged

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height = 10)
knitr::opts_chunk$set(fig.width = 14)
```

```{r}
.libPaths(.Library)
library(tidyverse)
library(Seurat)
library(anndataR)
library(bigstatsr)
# devtools::load_all("../../anglemania")
library(matrixStats)
library(yaml)
```

# Load config
```{r}
cfg <- read_yaml("/home/akollot/projects/CRC1588/dataset_integration/anglemania_benchmark/scripts/config_files/config_varying_batch_biovar_facScale0.1.yml")
```

# Load metrics
```{r}
# Extract relevant paths
metrics_path <- cfg$visualization$metrics_file
samplesheet_path <- cfg$samplesheet
outplot_bm <- cfg$visualization$outplot_dir_bm_visualization
# Ensure plot directories exist
if (!dir.exists(outplot_bm)) {
  dir.create(outplot_bm, recursive = TRUE, showWarnings = FALSE)
}

# Load data
metrics <- read.delim(metrics_path)
samplesheet <- read.delim(samplesheet_path)

metrics <- metrics %>%
  left_join(samplesheet %>% select(-original_h5ad), by = join_by(sample == sample_name)) %>%
  mutate(
    de.facLoc = factor(de.facLoc),
    batch.facLoc = factor(batch.facLoc),
    gene_selection = factor(gene_selection),
    integration_method = factor(integration_method)
  )  %>%
    mutate(
      de.facLoc = case_when(
        de.facLoc == 0 ~ "none",
        de.facLoc == 0.01 ~ "small",
        de.facLoc == 0.05 ~ "mild",
        de.facLoc == 0.1 ~ "moderate",
        de.facLoc == 0.3 ~ "strong",
        de.facLoc == 0.6 ~ "very strong",
      ),
      de.facLoc = factor(de.facLoc, levels = c("none", "small", "mild", "moderate", "strong", "very strong")),
      batch.facLoc = case_when(
        batch.facLoc == 0 ~ "none",
        batch.facLoc == 0.01 ~ "small",
        batch.facLoc == 0.05 ~ "mild",
        batch.facLoc == 0.1 ~ "moderate",
        batch.facLoc == 0.3 ~ "strong",
        batch.facLoc == 0.6 ~ "very strong",
      ),
      batch.facLoc = factor(batch.facLoc, levels = c("none", "small", "mild", "moderate", "strong", "very strong")),
      gene_selection = factor(gene_selection),
      integration_method = factor(integration_method)
    ) |>
    as_tibble()

head(metrics)
```



# Plot
## Heatmap integration score as a function of biol. variab. and batch effects
```{r}
for (m in unique(metrics$integration_method)) {
  for (i in unique(metrics$ngroup)) {
    for (j in unique(metrics$nbatch)) {
      p <- metrics %>%
        filter(ngroup == i, nbatch == j, integration_method == m) %>%
        ggplot(aes(x = batch.facLoc, y = de.facLoc)) +
        geom_tile(aes(fill = Total, color = Total)) +
        coord_equal() +
        labs(x = "Batch Effects", y = "Biological Variability", title = paste0(m, "-ngroup", i, "-nbatch", j, "-TotalScore"))
      print(p)
    }
  }
}
p <- metrics %>%
  ggplot(aes(x = batch.facLoc, y = de.facLoc)) +
  geom_tile(aes(fill = Total, color = Total)) +
  coord_equal() +
  scale_fill_viridis_c() +
  facet_wrap(~gene_selection+integration_method)
p

# p <- metrics %>% 
#   ggplot(aes(x = de.facLoc, y = Total))+
#   geom_point(aes(color = batch.facLoc, shape = gene_selection))+
#   facet_wrap(~gene_selection+integration_method)
# p

```

```{r}
for (m in unique(metrics$integration_method)) {
  for (g in unique(metrics$gene_selection)) {
    p <- metrics %>%
      filter(integration_method == m, gene_selection == g) %>%
      summarise(
        mean_score = mean(Total),
        median_score = median(Total),
        integration_method = m,
        de.facLoc = de.facLoc,
        batch.facLoc = batch.facLoc,
        .by = c(de.facLoc, batch.facLoc)
      ) %>%
      distinct() %>% 
      ggplot(aes(x = batch.facLoc, y = de.facLoc)) +
        geom_tile(aes(fill = mean_score)) +
        geom_text(aes(label = round(mean_score, 2)), color = "black", size = 4) +  # Add text to tiles
        scale_fill_gradient(low ="grey", high = "#64487A", limits=c(0,1))+
        coord_equal() +
        labs(x = "Batch Effects", y = "Biological Variability", title = paste0(m, " - ", g, " - mean Total Score"))
    print(p)
  }
}
```

```{r}
for (m in unique(metrics$integration_method)) {
  for (g in unique(metrics$gene_selection)) {
    p <- metrics %>%
      filter(integration_method == m, gene_selection == g) %>%
      summarise(
        mean_score = mean(Total),
        median_score = median(Total),
        integration_method = m,
        de.facLoc = de.facLoc,
        batch.facLoc = batch.facLoc,
        .by = c(de.facLoc, batch.facLoc)
      ) %>%
      distinct() %>% 
      ggplot(aes(x = batch.facLoc, y = de.facLoc)) +
        geom_tile(aes(fill = median_score)) +
        geom_text(aes(label = round(median_score, 2)), color = "black", size = 4) +  # Add text to tiles
        scale_fill_gradient(low ="grey", high = "#64487A", limits=c(0,1))+
        coord_equal() +
        labs(x = "Batch Effects", y = "Biological Variability", title = paste0(m, " - ", g, " - median Total Score"))
    print(p)
  }
}
```

## violin plots
### Total Score
```{r}
dodge <- position_dodge(width = 0.7)
for (m in unique(metrics$integration_method)) {
  for (i in unique(metrics$ngroup)) {
    for (j in unique(metrics$nbatch)) {
      p <- metrics %>%
        filter(ngroup == i, nbatch == j, integration_method == m) %>%
        ggplot(aes(x = as.factor(de.facLoc), y = Total)) +
        # geom_violin(aes(fill = gene_selection), position = dodge, width = 2)+
        geom_boxplot(width = 0.5, aes(fill = gene_selection), position = dodge) +
        geom_jitter(aes(fill = gene_selection), alpha = 0.7, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.7)) +
        # make manual color
        scale_fill_manual(values = c("angl" = "#64487A", "hvg" = "grey"))+
        theme_bw() +
        labs(x = "Biological Variability", y = "Integration Score", title = paste0(m, "-ngroup", i, "-nbatch", j )) +
        ylim(0, 1) +
        # increase font size of all text
        theme(
          text = element_text(size = 20, face = "bold"),
          aspect.ratio = 1,
          legend.position = c(0.8, 0.2)
        )

        print(p)
        ggsave(
            file.path(outplot_bm, paste0(m, "_ngroup", i, "_nbatch", j, "_TotalScore_violin.pdf")),
            width = 7,
            height = 7,
            plot = p
        )
    }
  }
}

```

```{r}
metrics %>%
  distinct(ngroup, nbatch)
dodge <- position_dodge(width = 0.7)

p <- metrics %>%
  filter(integration_method == "scvi") %>%
  ggplot(aes(x = as.factor(de.facLoc), y = Total)) +
  # geom_violin(aes(fill = gene_selection), position = dodge, width = 2)+
  geom_boxplot(width = 0.5, aes(fill = gene_selection), position = dodge) +
  geom_jitter(aes(fill = gene_selection), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.7)) +
  # make manual color
  # scale_color_brewer(palette = "Paired") +  # "Paired" is a good palette for qualitative factors
  theme_bw() +
  scale_fill_manual(values = c("angl" = "#64487A", "hvg" = "grey"))+
  labs(x = "Biological Variability", y = "Integration Score") +
  # increase font size of all text
  theme(
    text = element_text(size = 30, face = "bold"),
    aspect.ratio = 1,
    legend.position = c(0.9, 0.1)
  ) +
  facet_wrap(~ ngroup + nbatch, ncol = 5, labeller = "label_both")
p

metrics %>%
  distinct(ngroup, nbatch)
dodge <- position_dodge(width = 0.7)
p <- metrics %>%
  filter(integration_method == "scanorama") %>%
  ggplot(aes(x = as.factor(de.facLoc), y = Total)) +
  # geom_violin(aes(fill = gene_selection), position = dodge, width = 2)+
  geom_boxplot(width = 0.5, aes(fill = gene_selection), position = dodge) +
  geom_jitter(aes(fill = gene_selection), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.7)) +
  # make manual color
  # scale_color_brewer(palette = "Paired") +  # "Paired" is a good palette for qualitative factors
  theme_bw() +
  scale_fill_manual(values = c("angl" = "#64487A", "hvg" = "grey"))+
  labs(x = "Biological Variability", y = "Integration Score") +
  # increase font size of all text
  theme(
    text = element_text(size = 30, face = "bold"),
    aspect.ratio = 1,
    legend.position = c(0.9, 0.1)
  ) +
  facet_wrap(~ ngroup + nbatch, ncol = 5, labeller = "label_both")
p
```

### Bio.conservation
```{r}
dodge <- position_dodge(width = 0.7)
for (m in unique(metrics$integration_method)) {
  for (i in unique(metrics$ngroup)) {
    for (j in unique(metrics$nbatch)) {
      p <- metrics %>%
        filter(ngroup == i, nbatch == j, integration_method == m) %>%
        ggplot(aes(x = as.factor(de.facLoc), y = Bio.conservation)) +
        # geom_violin(aes(fill = gene_selection), position = dodge, width = 2)+
        geom_boxplot(width = 0.5, aes(fill = gene_selection), position = dodge) +
        geom_jitter(aes(fill = gene_selection), alpha = 0.7, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.7)) +
        # make manual color
        scale_fill_manual(values = c("angl" = "#64487A", "hvg" = "grey"))+
        theme_bw() +
        labs(x = "Biological Variability", y = "BioConservation Score", title = paste0(m, "-ngroup", i, "-nbatch", j )) +
        ylim(0, 1) +
        # increase font size of all text
        theme(
          text = element_text(size = 20, face = "bold"),
          aspect.ratio = 1,
          legend.position = c(0.8, 0.2)
        )

        print(p)
        ggsave(
            file.path(outplot_bm, paste0(m, "_ngroup", i, "_nbatch", j, "_BioConservation_violin.pdf")),
            width = 7,
            height = 7,
            plot = p
        )
    }
  }
}
```

### Batch.correction
```{r}
dodge <- position_dodge(width = 0.7)
for (m in unique(metrics$integration_method)) {
  for (i in unique(metrics$ngroup)) {
    for (j in unique(metrics$nbatch)) {
      p <- metrics %>%
        filter(ngroup == i, nbatch == j, integration_method == m) %>%
        ggplot(aes(x = as.factor(de.facLoc), y = Batch.correction)) +
        # geom_violin(aes(fill = gene_selection), position = dodge, width = 2)+
        geom_boxplot(width = 0.5, aes(fill = gene_selection), position = dodge) +
        geom_jitter(aes(fill = gene_selection), alpha = 0.7, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.7)) +
        # make manual color
        scale_fill_manual(values = c("angl" = "#64487A", "hvg" = "grey"))+
        theme_bw() +
        labs(x = "Biological Variability", y = "BatchCorrection score", title = paste0(m, "-ngroup", i, "-nbatch", j )) +
        ylim(0, 1) +
        # increase font size of all text
        theme(
          text = element_text(size = 20, face = "bold"),
          aspect.ratio = 1,
          legend.position = c(0.8, 0.2)
        )
      print(p)
      ggsave(
        file.path(outplot_bm, paste0(m, "_ngroup", i, "_nbatch", j, "_BatchCorrection_violin.pdf")),
        width = 7,
        height = 7,
        plot = p
      )
    }
  }
}
```

## low DE total integration score across increasing batch effect
```{r}
lowde <- metrics |>
    filter(de.facLoc == "moderate")

# scatter plot
lowde |>
    ggplot(aes(x = batch.facLoc, y = Total, fill = gene_selection)) +
    geom_boxplot() +
    theme_minimal() +
    facet_wrap(~integration_method)

lowde |>
    filter(nbatch == 5, ngroup == 2) |>
    ggplot(aes(x = batch.facLoc, y = Total, color = integration_method, shape = gene_selection)) +
    geom_point() +
    theme_minimal()
lowde |>
    filter(nbatch == 2, ngroup == 5) |>
    ggplot(aes(x = batch.facLoc, y = Total, color = integration_method, shape = gene_selection)) +
    geom_point() +
    theme_minimal()
```

# session Info
```{r}
sessionInfo()
```