---
title: "Simulate Single Cell data with different number of cells"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "/home/akollot/projects/CRC1588/dataset_integration/anglemania_benchmark/output/")})
output:
    html_document:
      toc: yes
      toc_float:
        collapsed: no
        smooth_scroll: no
      df_print: paged
---


# load packages
```{r}
.libPaths(.Library)
suppressPackageStartupMessages({
    library(splatter)
    library(stringr)
    library(dplyr)
    options(Seurat.object.assay.version = "v3")
    library(SingleCellExperiment)
})
```

# set up parameters
## make samplesheet
```{r}
dparams = expand.grid(
    batch.facLoc = 0.1, # Strength of batch effect
    de.facLoc    = 0.1, # Biological variability
    nbatch       = 3, # Number of batches
    ngroup       = 3, # Number of cell types
    groupCells = c(50, 100, 250, 500, 600, 700, 800, 900, 1000), # Number of cells per cell type (adjust as needed)
    stringsAsFactors = FALSE
)
names(dparams)

outdir <- "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/test_numcells/h5ad"
if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE)
}
samplesheet <- dparams %>%
    mutate(sample_name = across(everything(), ~ paste0(cur_column(), .x))) %>%
    rowwise() %>%
    mutate(sample_name = paste(sample_name, collapse = "_")) %>%
    ungroup() %>%
    mutate(original_h5ad = file.path(outdir, paste0(sample_name, ".h5ad"))) %>%
    select(sample_name, original_h5ad, everything()) %>%
    distinct() %>%
    mutate(
        nGenes = 10000,
        de.facScale = 0.1
    )
colnames(samplesheet)


```

```{r}
samplesheet$file_path <- samplesheet$original_h5ad
write.table(samplesheet, file = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/test_numcells/samplesheet.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```


# simulation function
```{r}
#' splatter parameters to list
#' @description Convert splatter params object to list
#' @param obj sce object generated by splatter
#' @return list of splatter parameters
splatparams_to_list <- function(obj) {
    p <- metadata(obj)$Params
    slots <- slotNames(p)
    l <- setNames(lapply(slots, function(s) slot(p, s)), slots)
    return(l)
}
#' @description Create a scRNA-seq simulation using splatter
#' and save it to h5ad using anndataR
#' @param sample_name Name of the sample
#' @param ngroup Number of cell types
#' @param nbatch Number of batches
#' @param groupCells Number of cells per cell type
#' @param batch.facLoc Location of batch effect
#' @param batch.facScale Scale of batch effect
#' @param de.facLoc Location of biological variability
#' @param de.facScale Scale of biological variability
#' @param outfile Output file
#' @param ... Additional arguments passed to splatSimulate
#' @return NULL
# #' @export
create_and_save_sim <- function(
    sample_name,
    ngroup,
    nbatch,
    groupCells,
    batch.facLoc,
    de.facLoc,
    batch.facScale = 0.1, # splatter default
    de.facScale = 0.2, # default de.facScale is 0.4 but this is quite extreme!!
    nGenes = 10000, # splatter default
    outfile,
    ...){
    library(splatter)
    library(dplyr)
    library(anndataR)
    library(SingleCellExperiment)
    
    if (!file.exists(outfile)) {
        print(paste0("Processing ", sample_name, " with params:"))
        print(knitr::kable(cbind(ngroup, nbatch, batch.facLoc, de.facLoc)))
        set.seed(42)
        message("Simulating data")

        sim = splatSimulate(
            batchCells = rep(groupCells * ngroup, nbatch),
            group.prob = rep(1 / ngroup, ngroup),
            batch.facLoc = batch.facLoc,
            batch.facScale = batch.facScale,
            batch.rmEffect = ifelse(batch.facLoc == 0, TRUE, FALSE),
            #when batch.facLoc is 0, remove batch effect
            method = "groups",
            verbose = FALSE,
            out.prob = 0.001,
            de.prob = 0.1,
            de.facLoc = de.facLoc,
            de.facScale = ifelse(de.facLoc == 0, 0, de.facScale),
            # default de.facScale is 0.4 but this is quite extreme!!
            bcv.common = 0.1,
            nGenes = nGenes,
            ...
        )

        counts <- t(counts(sim)) %>% as.matrix() # for AnnData the matrix is transposed: Gene in columns Cells in rows
        metadata <- colData(sim) %>% as.data.frame()
        var <- rowData(sim) %>% as.data.frame()
        uns <- splatparams_to_list(sim)

        message("Creating AnnData object")
        adata <- anndataR::AnnData(
            X = counts,
            obs = metadata,
            var = var,
            uns = uns
        )
        message(paste0("Saving ", outfile))
        # file.remove(outfile)
        anndataR::write_h5ad(adata, path = outfile, mode = "w", compression = "none")
    } else {
        message(paste0(outfile, " already exists. Skipping..."))
    }
}
```


# run and save simulations
```{r}
library(doMC)
registerDoMC(10)
foreach(i = seq_len(nrow(samplesheet))) %dopar% {
    set.seed(42)
    dparam <- samplesheet[i, ]
    create_and_save_sim(
        sample_name = dparam$sample_name,
        ngroup = dparam$ngroup,
        nbatch = dparam$nbatch,
        groupCells = dparam$groupCells,
        batch.facLoc = dparam$batch.facLoc,
        de.facLoc = dparam$de.facLoc,
        de.facScale = dparam$de.facScale,
        nGenes = dparam$nGenes,
        outfile = dparam$original_h5ad
    )
}
```

