```{r}
suppressPackageStartupMessages({
    library(splatter)
    library(stringr)
    library(dplyr)
    library(tidyverse)
    library(tibble)
    library(jsonlite)
    library(pbapply)
    library(anndataR)
})
```

# Create parameters for simulation scenarios with different dropout rates 
* use dropout.mid argument in splatter
* use one combination of nbatch and ngroup only => otherwise it gets unnecessarily big

```{r}
facLocs <- c(0.05, 0.1, 0.3)
dparams <- expand.grid(
    batch.facLoc = facLocs, # Strength of batch effect
    de.facLoc = facLocs, # Biological variability
    nbatch = 4, # Number of batches
    ngroup =  3, # Number of cell types
    groupCells = 1000, # Number of cells per cell type (adjust as needed)
    stringsAsFactors = FALSE,
    dropout.mid = c(1, 1.5, 2, 2.5, 3, 3.5),
    dropout.shape = -1
)
names(dparams)

outdir <- "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/own_sim"
samplesheet_dropout <- dparams %>%
    mutate(sample_name = across(everything(), ~ paste0(cur_column(), .x))) %>%
    rowwise() %>%
    mutate(sample_name = paste(sample_name, collapse = "_")) %>%
    ungroup() %>%
    mutate(original_h5ad = file.path(outdir, paste0(sample_name, ".h5ad"))) %>%
    select(sample_name, original_h5ad, everything()) %>%
    distinct()
colnames(samplesheet_dropout)

samplesheet_dropout$file_path <- samplesheet_dropout$original_h5ad
write.table(samplesheet_dropout, file = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/own_sim/samplesheet.tsv", sep = "\t", row.names = FALSE, quote = FALSE)

```


# simulation function
```{r}
#' splatter parameters to list
#' @description Convert splatter params object to list
#' @param obj sce object generated by splatter
#' @return list of splatter parameters
splatparams_to_list <- function(obj) {
    p <- metadata(obj)$Params
    slots <- slotNames(p)
    l <- setNames(lapply(slots, function(s) slot(p, s)), slots)
    return(l)
}
#' @description Create a scRNA-seq simulation using splatter
#' and save it to h5ad using anndataR
#' @param sample_name Name of the sample
#' @param ngroup Number of cell types
#' @param nbatch Number of batches
#' @param groupCells Number of cells per cell type
#' @param batch.facLoc Location of batch effect
#' @param batch.facScale Scale of batch effect
#' @param de.facLoc Location of biological variability
#' @param de.facScale Scale of biological variability
#' @param outfile Output file
#' @param ... Additional arguments passed to splatSimulate
#' @return NULL
# #' @export
create_sim <- function(
    sample_name,
    ngroup,
    nbatch,
    groupCells,
    batch.facLoc,
    de.facLoc,
    batch.facScale = 0.1, # splatter default
    de.facScale = 0.2, # default de.facScale is 0.4 but this is quite extreme!!
    nGenes = 10000, # splatter default
    dropout.mid,
    dropout.shape,
    dropout.type = "experiment",
    ...){
    library(splatter)
    library(dplyr)
    library(anndataR)
    library(SingleCellExperiment)

    sim = splatSimulate(
            batchCells = rep(groupCells * ngroup, nbatch),
            group.prob = rep(1 / ngroup, ngroup),
            batch.facLoc = batch.facLoc,
            batch.facScale = batch.facScale,
            batch.rmEffect = ifelse(batch.facLoc == 0, TRUE, FALSE),
            # when batch.facLoc is 0, remove batch effect
            method = "groups",
            verbose = FALSE,
            out.prob = 0.001,
            de.prob = 0.1,
            de.facLoc = de.facLoc,
            de.facScale = ifelse(de.facLoc == 0, 0, de.facScale),
            # default de.facScale is 0.4 but this is quite extreme!!
            bcv.common = 0.1,
            nGenes = nGenes,
            dropout.mid = dropout.mid,
            dropout.shape = dropout.shape,
            dropout.type = dropout.type,
            ...
        )
}
    
save_sim <- function(sim, outfile) {
        counts <- t(counts(sim)) %>% as.matrix() # for AnnData the matrix is transposed: Gene in columns Cells in rows
        metadata <- colData(sim) %>% as.data.frame()
        var <- rowData(sim) %>% as.data.frame()
        uns <- splatparams_to_list(sim)

        message("Creating AnnData object")
        adata <- anndataR::AnnData(
            X = counts,
            obs = metadata,
            var = var,
            uns = uns
        )
        message(paste0("Saving ", outfile))
        # file.remove(outfile)
        anndataR::write_h5ad(adata, path = outfile, mode = "w", compression = "none")
}

create_and_save_sim <- function(
    sample_name,
    ngroup,
    nbatch,
    groupCells,
    batch.facLoc,
    de.facLoc,
    batch.facScale = 0.1, # splatter default
    de.facScale = 0.2, # default de.facScale is 0.4 but this is quite extreme!!
    nGenes = 10000, # splatter default
    dropout.mid,
    dropout.shape,
    dropout.type = "experiment",
    outfile,
    ...){
    if (!file.exists(outfile)) {
        print(paste0("Processing ", sample_name, " with params:"))
        print(knitr::kable(cbind(ngroup, nbatch, batch.facLoc, de.facLoc)))
        set.seed(42)
        message("Simulating data")

    sim <- create_sim(
        sample_name = sample_name,
        ngroup = ngroup,
        nbatch = nbatch,
        groupCells = groupCells,
        batch.facLoc = batch.facLoc,
        de.facLoc = de.facLoc,
        batch.facScale = batch.facScale,
        de.facScale = de.facScale,
        nGenes = nGenes,
        dropout.mid = dropout.mid,
        dropout.shape = dropout.shape,
        dropout.type = dropout.type,
        ...
    )

    save_sim(sim, outfile)
    message(paste0("Saved ", outfile))

    } else {
        message(paste0(outfile, " already exists. Skipping..."))
    }
}
```

# run and save simulations
```{r}
library(doMC)
registerDoMC(25)
foreach(i = seq_len(nrow(samplesheet_dropout)))%dopar%{
    set.seed(42)
    dparam <- samplesheet_dropout[i, ]
    create_and_save_sim(
        sample_name = dparam$sample_name,
        ngroup = dparam$ngroup,
        nbatch = dparam$nbatch,
        groupCells = dparam$groupCells,
        batch.facLoc = dparam$batch.facLoc,
        de.facLoc = dparam$de.facLoc,
        dropout.mid = dparam$dropout.mid,
        dropout.shape = dparam$dropout.shape,
        outfile = dparam$file_path
    )
}
```

# temporary
## 16.09.25
```{r}
test1 <- read_h5ad(samplesheet_dropout$file_path[1])
sum(test1$X == 0) / (nrow(test1$X) * ncol(test1$X))

test2 <- read_h5ad(samplesheet_dropout$file_path[25])
sum(test2$X == 0) / (nrow(test2$X) * ncol(test2$X))

test3 <- read_h5ad(samplesheet_dropout$file_path[50])
sum(test3$X == 0) / (nrow(test3$X) * ncol(test3$X))
```

## old
```{r}
create_and_save_sim_temp <- function(
    sample_name,
    ngroup,
    nbatch,
    groupCells,
    batch.facLoc,
    de.facLoc,
    dropout.mid,
    dropout.shape
    ) {

    print(paste0("Processing ", sample_name, " with params:"))
    print(knitr::kable(cbind(ngroup, nbatch, batch.facLoc, de.facLoc, dropout.mid, dropout.shape)))
    set.seed(42)
    message("Simulating data")

    sim <- splatSimulate(
        batchCells = rep(groupCells * ngroup, nbatch),
        group.prob = rep(1 / ngroup, ngroup),
        batch.facLoc = batch.facLoc,
        batch.facScale = 0.1,
        method = "groups",
        verbose = FALSE,
        out.prob = 0.001,
        de.prob = 0.1,
        de.facLoc = de.facLoc,
        de.facScale = 0.1,
        bcv.common = 0.1,
        dropout.mid = dropout.mid,
        dropout.type = "experiment", # “experiment” is global dropout using the same set of parameters for every cell
        dropout.shape = dropout.shape
    )

    counts <- t(counts(sim)) %>% as.matrix() # for AnnData the matrix is transposed: Gene in columns Cells in rows
    metadata <- colData(sim) %>% as.data.frame()
    var <- rowData(sim) %>% as.data.frame()

    message("Creating AnnData object")
    adata <- anndataR::AnnData(
        X = counts,
        obs = metadata,
        var = var
    )
    return(adata)
}
```

```{r}
head(dparams)
filt_params <- samplesheet_low_facloc %>%
    filter(
        nbatch == 4,
        ngroup == 4,
        batch.facLoc == 0.1,
        de.facLoc == 0.1,
        dropout.mid == 1.5
    )

```

```{r}
adatas <- list()
for (i in 1:nrow(filt_params)) {
    set.seed(42)
    dparam <- filt_params[i, ]
    print(dparam)
    adatas[[as.character(dparam$dropout.shape)]] <- create_and_save_sim_temp(
        dparam$sample_name,
        dparam$ngroup,
        dparam$nbatch,
        dparam$groupCells,
        dparam$batch.facLoc,
        dparam$de.facLoc,
        dparam$dropout.mid,
        dparam$dropout.shape
    )
}


```

```{r}
# Define a function to calculate statistics for a given matrix:
calc_stats <- function(adata) {
    mat <- adata$X
    data.frame(
        mean   = mean(mat, na.rm = TRUE),
        median = median(mat, na.rm = TRUE),
        q25    = quantile(mat, 0.25, na.rm = TRUE),
        q75    = quantile(mat, 0.75, na.rm = TRUE)
    )
}

# Apply the function to each matrix in the list:
stats_list <- pblapply(adatas, calc_stats, cl = 5)

# Combine the list of data frames into a single data frame:
stats_df <- do.call(rbind, stats_list)
stats_df$k <- rownames(stats_df)
stats_df
stats_df %>%
    ggplot(aes(reorder(k, as.numeric(k)), mean)) +
    geom_point()



```

## estimate parameters from lueken theis dataset
```{r}
sce <- anndataR::read_h5ad("/local/Projects/AAkalin_Neuroblastoma/data/Luecken_Theis_NatMethods_2021_benchmarking/datasets/Lung_atlas_public.h5ad", to = "SingleCellExperiment")
counts(sce) <- as.matrix(counts(sce))
estimates_lung_atlas <- splatter::splatEstimate(sce)

sce <- anndataR::read_h5ad("/local/Projects/AAkalin_Neuroblastoma/data/Luecken_Theis_NatMethods_2021_benchmarking/datasets/Immune_ALL_human.h5ad", to = "SingleCellExperiment")
counts(sce) <- as.matrix(counts(sce))
estimates_immune_all <- splatter::splatEstimate(sce)
default <- newSplatParams()
```

```{r}
slots <- slotNames(estimates_lung_atlas)
estimates_lung_atlas_df <- setNames(lapply(slots, function(s) slot(estimates_lung_atlas, s)), slots) %>%
    as.data.frame()

slots <- slotNames(estimates_immune_all)
estimates_immune_all_df <- setNames(lapply(slots, function(s) slot(estimates_immune_all, s)), slots) %>%
    as.data.frame()

slots <- slotNames(default)
default_df <- setNames(lapply(slots, function(s) slot(default, s)), slots) %>%
    as.data.frame()


compare_df <- rbind(estimates_lung_atlas_df, estimates_immune_all_df, default_df)
```

```{r}
groupCells <- 500
ngroup <- 3
nbatch <- 2
mean.rate <- 4
lib.loc <- 9 # ≈ 4 000 UMIs median depth
lib.scale <- 0.75
bcv.common <- 0.25
bcv.df <- 18
batch.facLoc <- 0.1
de.facLoc <- 0.1
de.facScale <- 0.1
# dropout.mids <- c(-1.2, -0.6, 0, 0.6, 1.1) # as in the table
dropout.mids <- c(2.5, 3, 3.5, 4, 4.5)
dropout.shape <- -1
for (i in 1:length(dropout.mids)) {
    dropout.mid <- dropout.mids[i]
    sim <- splatSimulate(
        batchCells = rep(groupCells * ngroup, nbatch),
        group.prob = rep(1 / ngroup, ngroup),
        batch.facLoc = batch.facLoc,
        batch.facScale = 0.1,
        method = "group",
        verbose = FALSE,
        # mean.rate = mean.rate,
        # lib.loc = lib.loc,
        # lib.scale = lib.scale,
        # bcv.common = bcv.common,
        # bcv.df = bcv.df,
        de.prob = 0.1,
        de.facLoc = de.facLoc,
        de.facScale = de.facScale,
        dropout.mid = dropout.mid,
        dropout.shape = dropout.shape,
        dropout.type = "experiment"
    )
    # calculate sparsity
    n <- ncol(sim) * nrow(sim)
    sparsity <- sum(counts(sim) == 0) / n * 100
    print(paste0("Dropout mid: ", dropout.mid, " Sparsity: ", sparsity))
}
```
